name: countries_client
description: A graphql client for accessing the Countries API.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  ferry: ^0.10.4
  gql_http_link: ^0.4.0
dev_dependencies: 
  build_runner: ^2.0.6
  ferry_generator: ^0.4.4
  pedantic: ^1.10.0
  test: ^1.16.0